### PR TITLE
Added white list support for access checking.

### PR DESCRIPTION
**Pull request by ManuelGysin**
This will add a new argument which allowing specifying a white list with torrents allowed to be shared.
The white list must contain per line one torrent hash.

### CODE REVIEW

**Comment by stuaxo** [comment]
From a security POV, it you may not want to let the remote client know there is a whitelist (e.g. something like "Unknown torrent" might be better here)

A couple of code things that might be worth fixing:

- The name "self.ihs" doesn't make it clear that it is a _whitelist_ of infohashes, having whitelist in the name might make this clearer.

- Using a set instead of a list for the whitelist should be more performant.

- It would be really useful to be able to add / remove torrents from the whitelist at runtime.

**Comment by ManuelGysin** [comment]
Hello!

I've made the requested changed, can you please review?

Thanks
Manuel

**Comment by elektito** [comment]
Thanks for the pull request. I'm reviewing the changes and will be merging it soon if everything is all right.

**Comment by elektito** [comment]
Okay. I've reviewed the commits. I have a few small problems with this:

 - The whitelist should be optional. At the moment, the `watcher_whitelist` attempts opening the whitelist file, even if there is none. You'll see the error when Ctrl-C is pressed. You can launch that task only when there is a whitelist and in any case you should be prepared for the file to be deleted midways.
 - There are a few empty lines with spaces in them. Please remove the extra spaces. Empty lines should be empty.
 - Add spaces around the `^` operator while you're at it!
 - In the `--whitelist` argument description, please use "infohashes" instead of "IHs".

Apart from these, everything seems to be in order.

**Comment by ManuelGysin** [comment]
Hello

Thanks for the review, I've adjusted the points you mentioned. File is now PEP8 valid, except for some lines that are long then 79 characters.
For the logic I've adjusted --whitelist to --white-list, in this case the argument is now the in the same syntax as --log-level and so on.

Greets
Manuel

**Comment by elektito** [comment]
Sorry to be nitpicky but I've got a couple more problems:

 - "whitelist" is actually a single word. "White list" is a list that happens to be white. So `--whitelist` is the correct usage.
 - Please use `asyncio.ensure_future` for creating tasks instead of `create_task`.
 - Please make `allowed_torrents` an optional argument.
 - I'm not too fussed about longer-than-80-character lines, but when there is a nice way to break the line, I'd go with shorter lines. For example this line:

        tracker = TrackerServer(local_addr=args.bind, loop=loop, allowed_torrents=allowed_torrents)

    could easily be broken into this:

        tracker = TrackerServer(local_addr=args.bind,
                                loop=loop,
                                allowed_torrents=allowed_torrents)

**Comment by elektito** [comment]
I merged your changes, with a few updates of my own. It's not mergeable with your branch I'm afraid, but didn't seem to be a concern of yours given that you weren't using real commit messages. You'll need to reset you repo or clone again. Sorry about that but I'm new to this game.

**Comment by ManuelGysin** [comment]
Hello!

Thanks for the merge. Sorry had to work the whole Sunday and couldn't prepare a proper commit. 

Thanks again and greets
Manuel

**Pull request closed without merging**
